### ISSUE TITLE
Make-Error

### ISSUE THREAD

**Issue by maede97** [guetzli32/GraphLib#20]
Doxygen build started
/home/matthias/Documents/GraphLib/test/Test_ListGraph.cpp: In function ‘int main(int, const char**)’:
/home/matthias/Documents/GraphLib/test/Test_ListGraph.cpp:29:52: error: no matching function for call to ‘gl::Graph<int, gl::List, gl::Directed>::getNodeDegree(int)’
   std::cout << "Degree of 2: " << g.getNodeDegree(2) << std::endl;
                                                    ^
In file included from /home/matthias/Documents/GraphLib/graphlib/src/structures/Edge.hpp:4:0,
                 from /home/matthias/Documents/GraphLib/graphlib/structures:10,
                 from /home/matthias/Documents/GraphLib/graphlib/gl:4,
                 from /home/matthias/Documents/GraphLib/test/Test_ListGraph.cpp:1:
/home/matthias/Documents/GraphLib/graphlib/src/structures/Graph.hpp:1800:16: note: candidate: template<class DIR, class STORAGE, std::enable_if_t<(is_same_v<STORAGE, gl::List> && is_same_v<DIR, gl::Undirected>), int>* <anonymous> > gl::Graph<SCALAR, STORAGE_KIND, DIRECTION>::idx_t gl::Graph<SCALAR, STORAGE_KIND, DIRECTION>::getNodeDegree(const idx_t&) const [with DIR = DIR; STORAGE = STORAGE; std::enable_if_t<(is_same_v<STORAGE, gl::List> && is_same_v<DIR, gl::Undirected>), int>* <anonymous> = <enumerator>; SCALAR = int; STORAGE_KIND = gl::List; DIRECTION = gl::Directed]
   inline idx_t getNodeDegree(const idx_t &id) const
                ^~~~~~~~~~~~~
/home/matthias/Documents/GraphLib/graphlib/src/structures/Graph.hpp:1800:16: note:   template argument deduction/substitution failed:
In file included from /home/matthias/Documents/GraphLib/graphlib/structures:4:0,
                 from /home/matthias/Documents/GraphLib/graphlib/gl:4,
                 from /home/matthias/Documents/GraphLib/test/Test_ListGraph.cpp:1:
/home/matthias/Documents/GraphLib/graphlib/src/partial_specialization_on:37:155: note: invalid template non-type parameter
 #define GL_ENABLE_IF_LIST_UNDIRECTED template <typename DIR = DIRECTION, typename STORAGE = STORAGE_KIND, std::enable_if_t<GL_IS_LIST_UNDIRECTED, int>* = nullptr>
                                                                                                                                                           ^
/home/matthias/Documents/GraphLib/graphlib/src/structures/Graph.hpp:1798:3: note: in expansion of macro ‘GL_ENABLE_IF_LIST_UNDIRECTED’
   GL_ENABLE_IF_LIST_UNDIRECTED
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/matthias/Documents/GraphLib/graphlib/src/structures/Edge.hpp:4:0,
                 from /home/matthias/Documents/GraphLib/graphlib/structures:10,
                 from /home/matthias/Documents/GraphLib/graphlib/gl:4,
                 from /home/matthias/Documents/GraphLib/test/Test_ListGraph.cpp:1:
/home/matthias/Documents/GraphLib/graphlib/src/structures/Graph.hpp:1809:9: note: candidate: template<class DIR, class STORAGE, std::enable_if_t<(is_same_v<STORAGE, gl::Matrix> && is_same_v<DIR, gl::Undirected>), int>* <anonymous> > gl::Graph<SCALAR, STORAGE_KIND, DIRECTION>::idx_t gl::Graph<SCALAR, STORAGE_KIND, DIRECTION>::getNodeDegree(const idx_t&) const [with DIR = DIR; STORAGE = STORAGE; std::enable_if_t<(is_same_v<STORAGE, gl::Matrix> && is_same_v<DIR, gl::Undirected>), int>* <anonymous> = <enumerator>; SCALAR = int; STORAGE_KIND = gl::List; DIRECTION = gl::Directed]
   idx_t getNodeDegree(const idx_t &id) const
         ^~~~~~~~~~~~~
/home/matthias/Documents/GraphLib/graphlib/src/structures/Graph.hpp:1809:9: note:   template argument deduction/substitution failed:
In file included from /home/matthias/Documents/GraphLib/graphlib/structures:4:0,
                 from /home/matthias/Documents/GraphLib/graphlib/gl:4,
                 from /home/matthias/Documents/GraphLib/test/Test_ListGraph.cpp:1:
/home/matthias/Documents/GraphLib/graphlib/src/partial_specialization_on:35:159: note: invalid template non-type parameter
 #define GL_ENABLE_IF_MATRIX_UNDIRECTED template <typename DIR = DIRECTION, typename STORAGE = STORAGE_KIND, std::enable_if_t<GL_IS_MATRIX_UNDIRECTED, int>* = nullptr>
                                                                                                                                                               ^
/home/matthias/Documents/GraphLib/graphlib/src/structures/Graph.hpp:1808:3: note: in expansion of macro ‘GL_ENABLE_IF_MATRIX_UNDIRECTED’
   GL_ENABLE_IF_MATRIX_UNDIRECTED
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/matthias/Documents/GraphLib/graphlib/external:6:0,
                 from /home/matthias/Documents/GraphLib/test/Test_MathGLColors.cpp:2:
/home/matthias/Documents/GraphLib/graphlib/src/io/WriteImage.hpp: In instantiation of ‘void gl::external::saveImage(mglGraph*, gl::Graph<SCALAR, STORAGE_KIND, DIRECTION>&, const char*) [with SCALAR = double; STORAGE_KIND = gl::Matrix; DIRECTION = gl::Directed]’:
/home/matthias/Documents/GraphLib/test/Test_MathGLColors.cpp:19:39:   required from here
/home/matthias/Documents/GraphLib/graphlib/src/io/WriteImage.hpp:37:5: error: no matching function for call to ‘gl::Graph<double, gl::Matrix, gl::Directed>::getNodeDegree(gl::Graph<double, gl::Matrix, gl::Directed>::idx_t&)’
     triplets.emplace_back(i, i, g.getNodeDegree(i));
     ^~~~~~~~
In file included from /home/matthias/Documents/GraphLib/graphlib/src/structures/Edge.hpp:4:0,
                 from /home/matthias/Documents/GraphLib/graphlib/structures:10,
                 from /home/matthias/Documents/GraphLib/test/Test_MathGLColors.cpp:1:
/home/matthias/Documents/GraphLib/graphlib/src/structures/Graph.hpp:1800:16: note: candidate: template<class DIR, class STORAGE, std::enable_if_t<(is_same_v<STORAGE, gl::List> && is_same_v<DIR, gl::Undirected>), int>* <anonymous> > gl::Graph<SCALAR, STORAGE_KIND, DIRECTION>::idx_t gl::Graph<SCALAR, STORAGE_KIND, DIRECTION>::getNodeDegree(const idx_t&) const [with DIR = DIR; STORAGE = STORAGE; std::enable_if_t<(is_same_v<STORAGE, gl::List> && is_same_v<DIR, gl::Undirected>), int>* <anonymous> = <enumerator>; SCALAR = double; STORAGE_KIND = gl::Matrix; DIRECTION = gl::Directed]
   inline idx_t getNodeDegree(const idx_t &id) const
                ^~~~~~~~~~~~~
/home/matthias/Documents/GraphLib/graphlib/src/structures/Graph.hpp:1800:16: note:   template argument deduction/substitution failed:
In file included from /home/matthias/Documents/GraphLib/graphlib/structures:4:0,
                 from /home/matthias/Documents/GraphLib/test/Test_MathGLColors.cpp:1:
/home/matthias/Documents/GraphLib/graphlib/src/partial_specialization_on:37:155: note: invalid template non-type parameter
 #define GL_ENABLE_IF_LIST_UNDIRECTED template <typename DIR = DIRECTION, typename STORAGE = STORAGE_KIND, std::enable_if_t<GL_IS_LIST_UNDIRECTED, int>* = nullptr>
                                                                                                                                                           ^
/home/matthias/Documents/GraphLib/graphlib/src/structures/Graph.hpp:1798:3: note: in expansion of macro ‘GL_ENABLE_IF_LIST_UNDIRECTED’
   GL_ENABLE_IF_LIST_UNDIRECTED
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/matthias/Documents/GraphLib/graphlib/src/structures/Edge.hpp:4:0,
                 from /home/matthias/Documents/GraphLib/graphlib/structures:10,
                 from /home/matthias/Documents/GraphLib/test/Test_MathGLColors.cpp:1:
/home/matthias/Documents/GraphLib/graphlib/src/structures/Graph.hpp:1809:9: note: candidate: template<class DIR, class STORAGE, std::enable_if_t<(is_same_v<STORAGE, gl::Matrix> && is_same_v<DIR, gl::Undirected>), int>* <anonymous> > gl::Graph<SCALAR, STORAGE_KIND, DIRECTION>::idx_t gl::Graph<SCALAR, STORAGE_KIND, DIRECTION>::getNodeDegree(const idx_t&) const [with DIR = DIR; STORAGE = STORAGE; std::enable_if_t<(is_same_v<STORAGE, gl::Matrix> && is_same_v<DIR, gl::Undirected>), int>* <anonymous> = <enumerator>; SCALAR = double; STORAGE_KIND = gl::Matrix; DIRECTION = gl::Directed]
   idx_t getNodeDegree(const idx_t &id) const
         ^~~~~~~~~~~~~
/home/matthias/Documents/GraphLib/graphlib/src/structures/Graph.hpp:1809:9: note:   template argument deduction/substitution failed:
In file included from /home/matthias/Documents/GraphLib/graphlib/structures:4:0,
                 from /home/matthias/Documents/GraphLib/test/Test_MathGLColors.cpp:1:
/home/matthias/Documents/GraphLib/graphlib/src/partial_specialization_on:35:159: note: invalid template non-type parameter
 #define GL_ENABLE_IF_MATRIX_UNDIRECTED template <typename DIR = DIRECTION, typename STORAGE = STORAGE_KIND, std::enable_if_t<GL_IS_MATRIX_UNDIRECTED, int>* = nullptr>
                                                                                                                                                               ^
/home/matthias/Documents/GraphLib/graphlib/src/structures/Graph.hpp:1808:3: note: in expansion of macro ‘GL_ENABLE_IF_MATRIX_UNDIRECTED’
   GL_ENABLE_IF_MATRIX_UNDIRECTED
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/matthias/Documents/GraphLib/graphlib/external:6:0,
                 from /home/matthias/Documents/GraphLib/test/Test_MathGLColors.cpp:2:
/home/matthias/Documents/GraphLib/graphlib/src/io/WriteImage.hpp:82:15: error: no matching function for call to ‘gl::Graph<double, gl::Matrix, gl::Directed>::getNodeDegree(gl::Graph<double, gl::Matrix, gl::Directed>::idx_t&)’
     pos /= (1 + g.getNodeDegree(i)); // Todo: nodes with high degree are now outside, they should be in the middle
            ~~~^~~~~~~~~~~~~~~~~~~~~
In file included from /home/matthias/Documents/GraphLib/graphlib/src/structures/Edge.hpp:4:0,
                 from /home/matthias/Documents/GraphLib/graphlib/structures:10,
                 from /home/matthias/Documents/GraphLib/test/Test_MathGLColors.cpp:1:
/home/matthias/Documents/GraphLib/graphlib/src/structures/Graph.hpp:1800:16: note: candidate: template<class DIR, class STORAGE, std::enable_if_t<(is_same_v<STORAGE, gl::List> && is_same_v<DIR, gl::Undirected>), int>* <anonymous> > gl::Graph<SCALAR, STORAGE_KIND, DIRECTION>::idx_t gl::Graph<SCALAR, STORAGE_KIND, DIRECTION>::getNodeDegree(const idx_t&) const [with DIR = DIR; STORAGE = STORAGE; std::enable_if_t<(is_same_v<STORAGE, gl::List> && is_same_v<DIR, gl::Undirected>), int>* <anonymous> = <enumerator>; SCALAR = double; STORAGE_KIND = gl::Matrix; DIRECTION = gl::Directed]
   inline idx_t getNodeDegree(const idx_t &id) const
                ^~~~~~~~~~~~~
/home/matthias/Documents/GraphLib/graphlib/src/structures/Graph.hpp:1800:16: note:   template argument deduction/substitution failed:
In file included from /home/matthias/Documents/GraphLib/graphlib/structures:4:0,
                 from /home/matthias/Documents/GraphLib/test/Test_MathGLColors.cpp:1:
/home/matthias/Documents/GraphLib/graphlib/src/partial_specialization_on:37:155: note: invalid template non-type parameter
 #define GL_ENABLE_IF_LIST_UNDIRECTED template <typename DIR = DIRECTION, typename STORAGE = STORAGE_KIND, std::enable_if_t<GL_IS_LIST_UNDIRECTED, int>* = nullptr>
                                                                                                                                                           ^
/home/matthias/Documents/GraphLib/graphlib/src/structures/Graph.hpp:1798:3: note: in expansion of macro ‘GL_ENABLE_IF_LIST_UNDIRECTED’
   GL_ENABLE_IF_LIST_UNDIRECTED
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/matthias/Documents/GraphLib/graphlib/src/structures/Edge.hpp:4:0,
                 from /home/matthias/Documents/GraphLib/graphlib/structures:10,
                 from /home/matthias/Documents/GraphLib/test/Test_MathGLColors.cpp:1:
/home/matthias/Documents/GraphLib/graphlib/src/structures/Graph.hpp:1809:9: note: candidate: template<class DIR, class STORAGE, std::enable_if_t<(is_same_v<STORAGE, gl::Matrix> && is_same_v<DIR, gl::Undirected>), int>* <anonymous> > gl::Graph<SCALAR, STORAGE_KIND, DIRECTION>::idx_t gl::Graph<SCALAR, STORAGE_KIND, DIRECTION>::getNodeDegree(const idx_t&) const [with DIR = DIR; STORAGE = STORAGE; std::enable_if_t<(is_same_v<STORAGE, gl::Matrix> && is_same_v<DIR, gl::Undirected>), int>* <anonymous> = <enumerator>; SCALAR = double; STORAGE_KIND = gl::Matrix; DIRECTION = gl::Directed]
   idx_t getNodeDegree(const idx_t &id) const
         ^~~~~~~~~~~~~
/home/matthias/Documents/GraphLib/graphlib/src/structures/Graph.hpp:1809:9: note:   template argument deduction/substitution failed:
In file included from /home/matthias/Documents/GraphLib/graphlib/structures:4:0,
                 from /home/matthias/Documents/GraphLib/test/Test_MathGLColors.cpp:1:
/home/matthias/Documents/GraphLib/graphlib/src/partial_specialization_on:35:159: note: invalid template non-type parameter
 #define GL_ENABLE_IF_MATRIX_UNDIRECTED template <typename DIR = DIRECTION, typename STORAGE = STORAGE_KIND, std::enable_if_t<GL_IS_MATRIX_UNDIRECTED, int>* = nullptr>
                                                                                                                                                               ^
/home/matthias/Documents/GraphLib/graphlib/src/structures/Graph.hpp:1808:3: note: in expansion of macro ‘GL_ENABLE_IF_MATRIX_UNDIRECTED’
   GL_ENABLE_IF_MATRIX_UNDIRECTED
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [test/CMakeFiles/ListGraph.dir/Test_ListGraph.cpp.o] Error 1
make[1]: *** [test/CMakeFiles/ListGraph.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: *** [test/CMakeFiles/MathGLColors.dir/Test_MathGLColors.cpp.o] Error 1
make[1]: *** [test/CMakeFiles/MathGLColors.dir/all] Error 2
make: *** [all] Error 2

**Comment by guetzli32** [comment]
Fixed.
